/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRepositoriesRouteImport } from './routes/_app.repositories'
import { Route as OauthSuccessRouteImport } from './routes/oauth.success'
import { Route as AppHistoryIndexRouteImport } from './routes/_app.history.index'
import { Route as AppHistoryPatchNotesIdRouteImport } from './routes/_app.history.$patchNotesId'
import { Route as AppRepositoriesIndexRouteImport } from './routes/_app.repositories.index'
import { Route as AppRepositoriesRepositoryIdIndexRouteImport } from './routes/_app.repositories.$repositoryId.index'
import { Route as AppRepositoriesRepositoryIdGenerateRouteImport } from './routes/_app.repositories.$repositoryId.generate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRoute = AppRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AppRoute,
} as any)
const OauthSuccessRoute = OauthSuccessRouteImport.update({
  id: '/oauth/success',
  path: '/oauth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryIndexRoute = AppHistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHistoryRoute,
} as any)
const AppHistoryPatchNotesIdRoute = AppHistoryPatchNotesIdRouteImport.update({
  id: '/$patchNotesId',
  path: '/$patchNotesId',
  getParentRoute: () => AppHistoryRoute,
} as any)
const AppRepositoriesIndexRoute = AppRepositoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRepositoriesRoute,
} as any)
const AppRepositoriesRepositoryIdIndexRoute =
  AppRepositoriesRepositoryIdIndexRouteImport.update({
    id: '/$repositoryId/',
    path: '/$repositoryId/',
    getParentRoute: () => AppRepositoriesRoute,
  } as any)
const AppRepositoriesRepositoryIdGenerateRoute =
  AppRepositoriesRepositoryIdGenerateRouteImport.update({
    id: '/$repositoryId/generate',
    path: '/$repositoryId/generate',
    getParentRoute: () => AppRepositoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/repositories': typeof AppRepositoriesRouteWithChildren
  '/oauth/success': typeof OauthSuccessRoute
  '/history/$patchNotesId': typeof AppHistoryPatchNotesIdRoute
  '/history/': typeof AppHistoryIndexRoute
  '/repositories/': typeof AppRepositoriesIndexRoute
  '/repositories/$repositoryId/generate': typeof AppRepositoriesRepositoryIdGenerateRoute
  '/repositories/$repositoryId/': typeof AppRepositoriesRepositoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/oauth/success': typeof OauthSuccessRoute
  '/history/$patchNotesId': typeof AppHistoryPatchNotesIdRoute
  '/history': typeof AppHistoryIndexRoute
  '/repositories': typeof AppRepositoriesIndexRoute
  '/repositories/$repositoryId/generate': typeof AppRepositoriesRepositoryIdGenerateRoute
  '/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/repositories': typeof AppRepositoriesRouteWithChildren
  '/oauth/success': typeof OauthSuccessRoute
  '/_app/history/$patchNotesId': typeof AppHistoryPatchNotesIdRoute
  '/_app/history/': typeof AppHistoryIndexRoute
  '/_app/repositories/': typeof AppRepositoriesIndexRoute
  '/_app/repositories/$repositoryId/generate': typeof AppRepositoriesRepositoryIdGenerateRoute
  '/_app/repositories/$repositoryId/': typeof AppRepositoriesRepositoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/repositories'
    | '/oauth/success'
    | '/history/$patchNotesId'
    | '/history/'
    | '/repositories/'
    | '/repositories/$repositoryId/generate'
    | '/repositories/$repositoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/dashboard'
    | '/profile'
    | '/oauth/success'
    | '/history/$patchNotesId'
    | '/history'
    | '/repositories'
    | '/repositories/$repositoryId/generate'
    | '/repositories/$repositoryId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demo'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/profile'
    | '/_app/repositories'
    | '/oauth/success'
    | '/_app/history/$patchNotesId'
    | '/_app/history/'
    | '/_app/repositories/'
    | '/_app/repositories/$repositoryId/generate'
    | '/_app/repositories/$repositoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  OauthSuccessRoute: typeof OauthSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories': {
      id: '/_app/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AppRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/success': {
      id: '/oauth/success'
      path: '/oauth/success'
      fullPath: '/oauth/success'
      preLoaderRoute: typeof OauthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/history/': {
      id: '/_app/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof AppHistoryIndexRouteImport
      parentRoute: typeof AppHistoryRoute
    }
    '/_app/history/$patchNotesId': {
      id: '/_app/history/$patchNotesId'
      path: '/$patchNotesId'
      fullPath: '/history/$patchNotesId'
      preLoaderRoute: typeof AppHistoryPatchNotesIdRouteImport
      parentRoute: typeof AppHistoryRoute
    }
    '/_app/repositories/': {
      id: '/_app/repositories/'
      path: '/'
      fullPath: '/repositories/'
      preLoaderRoute: typeof AppRepositoriesIndexRouteImport
      parentRoute: typeof AppRepositoriesRoute
    }
    '/_app/repositories/$repositoryId/': {
      id: '/_app/repositories/$repositoryId/'
      path: '/$repositoryId'
      fullPath: '/repositories/$repositoryId/'
      preLoaderRoute: typeof AppRepositoriesRepositoryIdIndexRouteImport
      parentRoute: typeof AppRepositoriesRoute
    }
    '/_app/repositories/$repositoryId/generate': {
      id: '/_app/repositories/$repositoryId/generate'
      path: '/$repositoryId/generate'
      fullPath: '/repositories/$repositoryId/generate'
      preLoaderRoute: typeof AppRepositoriesRepositoryIdGenerateRouteImport
      parentRoute: typeof AppRepositoriesRoute
    }
  }
}

interface AppHistoryRouteChildren {
  AppHistoryPatchNotesIdRoute: typeof AppHistoryPatchNotesIdRoute
  AppHistoryIndexRoute: typeof AppHistoryIndexRoute
}

const AppHistoryRouteChildren: AppHistoryRouteChildren = {
  AppHistoryPatchNotesIdRoute: AppHistoryPatchNotesIdRoute,
  AppHistoryIndexRoute: AppHistoryIndexRoute,
}

const AppHistoryRouteWithChildren = AppHistoryRoute._addFileChildren(
  AppHistoryRouteChildren,
)

interface AppRepositoriesRouteChildren {
  AppRepositoriesIndexRoute: typeof AppRepositoriesIndexRoute
  AppRepositoriesRepositoryIdGenerateRoute: typeof AppRepositoriesRepositoryIdGenerateRoute
  AppRepositoriesRepositoryIdIndexRoute: typeof AppRepositoriesRepositoryIdIndexRoute
}

const AppRepositoriesRouteChildren: AppRepositoriesRouteChildren = {
  AppRepositoriesIndexRoute: AppRepositoriesIndexRoute,
  AppRepositoriesRepositoryIdGenerateRoute:
    AppRepositoriesRepositoryIdGenerateRoute,
  AppRepositoriesRepositoryIdIndexRoute: AppRepositoriesRepositoryIdIndexRoute,
}

const AppRepositoriesRouteWithChildren = AppRepositoriesRoute._addFileChildren(
  AppRepositoriesRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppRepositoriesRoute: typeof AppRepositoriesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppRepositoriesRoute: AppRepositoriesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  OauthSuccessRoute: OauthSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
