spring:
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}

  application:
    name: patchpilot

  ai:
    google:
      genai:
        project-id: ${SPRING_AI_GOOGLE_GENAI_PROJECT_ID}
        api-key: ${SPRING_AI_GOOGLE_GENAI_API_KEY}
        chat:
          options:
            model: ${SPRING_AI_GOOGLE_GENAI_CHAT_OPTIONS_MODEL}
            temperature: ${SPRING_AI_GOOGLE_GENAI_CHAT_OPTIONS_TEMPERATURE}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.patchpilot.backend: DEBUG


